apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
    #server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/childs
    repoURL: https://github.com/kkingkill/kube-prometheus-stack-kustomize.git
    targetRevision: HEAD
