apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  kube-prometheus-stack-engineer
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: /overlays/engineer
    repoURL: https://github.com/kkingkill/kube-prometheus-stack-kustomize.git
    targetRevision: HEAD
  kustomize:
    enableHelm: true   # This appends --enable-helm to the kustomize build command
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    #test
