apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-local
  namespace: argocd
  labels:
    app.kubernetes.io/name: kube-prometheus-stack-local
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/kkingkill/kube-prometheus-stack-kustomize.git
    #path: ./kube-prometheus-stack-local/overlays/engineer/chart
    path: ./kube-prometheus-stack-local/overlays/engineer/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values1.yaml
      releaseName: kube-prometheus-stack-local
  syncPolicy:
    # syncOptions:
    #   - Replace=true
    automated:
      prune: true
      selfHeal: true
