
apiVersion: v2
name: prometheus-customized
type: application
version: 36.2.0
appVersion: 0.57.0

dependencies:
- name: kube-prometheus-stack
  version: 36.2.0
  repository: "file://../../base/"
- name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.9.*
- name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 3.3.*
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.31.*


