alertmanager:
  enabled: true
  alertmanagerSpec:
    storage: 
      volumeClaimTemplate:
        spec:
          #storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

grafana:


  persistence:
    type: pvc
    enabled: true
    storageClassName: gp2
    accessModes: ["ReadWriteOnce"]
    size: 5Gi

prometheus:
  enabled: true 
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]    
          resources:
            requests:
              storage: 10Gi
          #storageClassName: gp2

    retention: 14d





